package fedorovs.telegrambot.commands;

public enum Command {
    NONE,
    START,
    ABOUT_COMPANY,
    USEFUL_CONTENT,
    SERVICES,
    EVENTS,
    REPORT_ABOUT_NEW_ORDERS,
    STATISTICS_ABOUT_CURRENT_EVENTS,
    CONNECT_TO_MANAGER,
    ABOUT_SERVICE,
    ORDER,
    CREATE_ORDER,
    ABOUT_СATEGORY,
    ABOUT_EVENT,
    EVENT_REGISTRATION,
    CREATE_EVENT_REGISTRATION
}